### PR TITLE
Fix links to sign in and sign out

### PR DESCRIPTION
**Pull request by TheShinriel**
# Error: 

There is a link that not used the constant file
```ts
	const login = () => {
		router.replace('/login');
	}
```

# Solution:

Simply use the constant to don't go on `/login` but `/api/kobble/login`
```ts
	const login = () => {
		router.replace(routes.login);
	}
```

### CODE REVIEW

**Comment by kevinpiac** [comment]
Hey!

Thanks for this pull request, and willing to participate in Kobble. I really appreciate it!

I haven't looked into the code yet but the issue you're describing seems related to a misconfiguration and not to an issue with the SDK since everything is functional on our end.
 
Could you please check that you have configured the `middleware.ts` file properly as explained in the quickstart section, and under the right directory (most likely your `src` directory)?

Here's the quickstart guide mentioning the middleware.ts file: https://docs.kobble.io/learning/quickstart/next

Let me know if it worked.

**Comment by TheShinriel** [comment]
Thx,  

There was an error on the middleware on my poject, you right!

In addition to authMiddleware, for other purposes I had declared an `export async function middleware(req) {` which seems to be incompatible with the default export.
If I comment it, the redirect works.

I have not an other error, but I don't have analyse for now 😉

I have updated this PR to fix a hardcoded link to '/login' from the provider, that seem an error to me 😁

**Comment by kevinpiac** [comment]
Great! Assigning this to @aurelien-brabant  :)

**Comment by aurelleb** [comment]
Hi @TheShinriel thank you very much for your contribution.

This looks good to me, good catch!

**Pull request merged**
